name: Scraping
run-name: ${{ github.actor }} is updating available housing

on:
  schedule: 
  - cron: "0 4 * * *"
env: 
  API_KEY: ${{ secrets.API_KEY }}
jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install
      - run: tsc 
      - run: node dist/src/index.js


